# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Shane\IdeaProjects\rom-patcher-gui\gui\main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(633, 303)
        MainWindow.setMinimumSize(QtCore.QSize(633, 303))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.source_rom = QtWidgets.QLineEdit(self.centralwidget)
        self.source_rom.setGeometry(QtCore.QRect(20, 60, 371, 20))
        self.source_rom.setObjectName("source_rom")
        self.source_select = QtWidgets.QPushButton(self.centralwidget)
        self.source_select.setGeometry(QtCore.QRect(400, 60, 81, 23))
        self.source_select.setObjectName("source_select")
        self.input_patch = QtWidgets.QLineEdit(self.centralwidget)
        self.input_patch.setGeometry(QtCore.QRect(20, 20, 501, 20))
        self.input_patch.setText("")
        self.input_patch.setClearButtonEnabled(False)
        self.input_patch.setObjectName("input_patch")
        self.output_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.output_dir.setGeometry(QtCore.QRect(20, 100, 371, 20))
        self.output_dir.setText("")
        self.output_dir.setObjectName("output_dir")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(9, 9, 611, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.input_select = QtWidgets.QPushButton(self.frame)
        self.input_select.setGeometry(QtCore.QRect(520, 10, 81, 23))
        self.input_select.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.input_select.setCheckable(False)
        self.input_select.setObjectName("input_select")
        self.output_select = QtWidgets.QPushButton(self.centralwidget)
        self.output_select.setGeometry(QtCore.QRect(400, 100, 81, 23))
        self.output_select.setObjectName("output_select")
        self.output_open = QtWidgets.QPushButton(self.centralwidget)
        self.output_open.setGeometry(QtCore.QRect(490, 100, 121, 23))
        self.output_open.setObjectName("output_open")
        self.source_open = QtWidgets.QPushButton(self.centralwidget)
        self.source_open.setGeometry(QtCore.QRect(490, 60, 121, 23))
        self.source_open.setObjectName("source_open")
        self.results_box = QtWidgets.QTextEdit(self.centralwidget)
        self.results_box.setGeometry(QtCore.QRect(20, 160, 421, 101))
        self.results_box.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.results_box.setObjectName("results_box")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(17, 130, 591, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 140, 441, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.patch_button = QtWidgets.QPushButton(self.centralwidget)
        self.patch_button.setGeometry(QtCore.QRect(450, 160, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.patch_button.setFont(font)
        self.patch_button.setObjectName("patch_button")
        self.rom_open = QtWidgets.QPushButton(self.centralwidget)
        self.rom_open.setGeometry(QtCore.QRect(450, 210, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.rom_open.setFont(font)
        self.rom_open.setObjectName("rom_open")
        self.exit_app = QtWidgets.QPushButton(self.centralwidget)
        self.exit_app.setGeometry(QtCore.QRect(450, 240, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.exit_app.setFont(font)
        self.exit_app.setObjectName("exit_app")
        self.frame.raise_()
        self.source_rom.raise_()
        self.source_select.raise_()
        self.input_patch.raise_()
        self.output_dir.raise_()
        self.output_select.raise_()
        self.output_open.raise_()
        self.source_open.raise_()
        self.results_box.raise_()
        self.line.raise_()
        self.label.raise_()
        self.patch_button.raise_()
        self.rom_open.raise_()
        self.exit_app.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.file_input_select = QtWidgets.QAction(MainWindow)
        self.file_input_select.setObjectName("file_input_select")
        self.file_source_select = QtWidgets.QAction(MainWindow)
        self.file_source_select.setObjectName("file_source_select")
        self.file_output_select = QtWidgets.QAction(MainWindow)
        self.file_output_select.setObjectName("file_output_select")
        self.help_help = QtWidgets.QAction(MainWindow)
        self.help_help.setObjectName("help_help")
        self.help_about = QtWidgets.QAction(MainWindow)
        self.help_about.setObjectName("help_about")
        self.file_save_settings = QtWidgets.QAction(MainWindow)
        self.file_save_settings.setObjectName("file_save_settings")
        self.file_exit_app = QtWidgets.QAction(MainWindow)
        self.file_exit_app.setObjectName("file_exit_app")
        self.menuFile.addAction(self.file_input_select)
        self.menuFile.addAction(self.file_source_select)
        self.menuFile.addAction(self.file_output_select)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.file_save_settings)
        self.menuFile.addAction(self.file_exit_app)
        self.menuHelp.addAction(self.help_help)
        self.menuHelp.addAction(self.help_about)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.input_patch, self.source_rom)
        MainWindow.setTabOrder(self.source_rom, self.source_select)
        MainWindow.setTabOrder(self.source_select, self.output_dir)
        MainWindow.setTabOrder(self.output_dir, self.output_select)
        MainWindow.setTabOrder(self.output_select, self.patch_button)
        MainWindow.setTabOrder(self.patch_button, self.rom_open)
        MainWindow.setTabOrder(self.rom_open, self.input_select)
        MainWindow.setTabOrder(self.input_select, self.source_open)
        MainWindow.setTabOrder(self.source_open, self.output_open)
        MainWindow.setTabOrder(self.output_open, self.results_box)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rom Patcher"))
        self.source_rom.setPlaceholderText(_translate("MainWindow", "Source ROM - Super Mario World ROM File (*.smc *.sfc)"))
        self.source_select.setText(_translate("MainWindow", "Select File"))
        self.input_patch.setPlaceholderText(_translate("MainWindow", "SMW Central URL / Patch URL / Patch File (*.ips *.bps *.zip)"))
        self.output_dir.setPlaceholderText(_translate("MainWindow", "Output Directory for Patched ROM Hack File"))
        self.input_select.setText(_translate("MainWindow", "Select File"))
        self.output_select.setText(_translate("MainWindow", "Select File"))
        self.output_open.setText(_translate("MainWindow", "Open Directory"))
        self.source_open.setText(_translate("MainWindow", "Open Directory"))
        self.label.setText(_translate("MainWindow", "Status:"))
        self.patch_button.setText(_translate("MainWindow", "Patch ROM"))
        self.rom_open.setText(_translate("MainWindow", "Open Directory"))
        self.exit_app.setText(_translate("MainWindow", "Exit Application"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.file_input_select.setText(_translate("MainWindow", "Select Patch File"))
        self.file_source_select.setText(_translate("MainWindow", "Select Source ROM"))
        self.file_output_select.setText(_translate("MainWindow", "Select Output Directory"))
        self.help_help.setText(_translate("MainWindow", "Help"))
        self.help_about.setText(_translate("MainWindow", "About"))
        self.file_save_settings.setText(_translate("MainWindow", "Save Settings"))
        self.file_exit_app.setText(_translate("MainWindow", "Exit"))

